version: '3'

services:
  database:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql:/var/lib/mysql
      - .:/usr/src/app
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
  
  adminer:
    image: adminer:4
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: database
    depends_on:
      - database
volumes:
  mysql:
  